apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ON7hZPrh1rMfJ1T6+soUm95Y9+lxQmkbcnfJXkM4LCztp69t,iv:FE0f7GaV0aFglqkSIInmW3xdOZKAnmqVc2O2qntv7Zk=,tag:HzHHflcmxCmEv+lZtCRDfg==,type:str]
    credentials.json: ENC[AES256_GCM,data:19lbWxLbkV9tmQ0xwgXy6mgoFMdwWpgTcXE1La50wOy9NMViUA48xXu2VeJUCFDNLYBL/JiVL9fuN0PgoryL3xQGg+GItFNOolKRK881UrCsqVrLUZQ5Z5cyRkw0YnZYl2nAMGRJoiXr3mI5wBqFuUQjZgHk2dwmH/9gp1dx4dlQ8qkCf+GmlFj+ImF/8/84yRKbH/V67AdbSYzFEsLne5jBtLFCGh/2V2CA2FyCOw==,iv:6XHCDGzMHlp2wfU468dNQ22mVctuZaRBrxCrTRRAL2A=,tag:tMkPBAtf0echzuGHt6qlIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeEhtSmEvbFQvQjdrL1hp
            by9LQ1dMTzY2Zkk2UlZsNjhGNXRTY1JVb1I4CkRnakxsK0FVSytSRExPZDFVYzhG
            SmRBd2lqdUR6VHZBcmZrWEpCYTZ0cUkKLS0tIHhuVk5XRzdCaEJydDJRTldiYkFW
            U1YvZ1JtWURWalk0MWo2b0ZpU1lBUlkKu5SGzkQc+Vm8+6O8zIFXgAE+FIbfeaeT
            mQSy9OPFMp+jfX4EjhnfVp6HSsdTsY1bYjQ1RVPidlwGbA+fJuKP+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T19:41:38Z"
    mac: ENC[AES256_GCM,data:ygH0H+Tz4RSs5kLyZb8tAu+hpGoNCUmVWSUwqaxGG5nWCzgmW+lhAeosibqduTym5wAaHH08h6ciB9ldPhDK/qNKujX3i09U4HBhtdnNOc5L5iw7EMUJGLlkEdgrr0g13ccIhAh9mwaWqEaYfRZmbBs5HH9KHzz0UPrzgGb0OiA=,iv:F8s/2AXs1vmKlN5kOQW7VjQMaBQtumSn1/VGm3EZhwM=,tag:EmozphauJH1UkDOkFOs2LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
