apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HywmgHLnnttS+gTqu7dkNFkX5ODOPTxMf67S8aLC/zPcSoh/,iv:rmXaRJxu3QqQqigJbkbtCfr8pAEhvP4K1GSIBxq6C2Q=,tag:Ao98lQjqw9H8mGWRpTGUUQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:xeUNGJ+0WhMXmjqLN63qGZot7lZFpaptBBSnUBQmsPhz0IujukGR7kZo2jzE3s6ed+xXz8cuAgnoRwdfaIuUAL0edS2Tq7xjZi0jXc675Ph16Q87uCdrDJ8UfFiJOWbIyhK1lKB4KjhJf3aGTjsDv5u1iR2N22uRhZ4HGZLIUF8vX/s3/+4xI6EQ58GoMGNg753KI648HuXWL/kmmRoNpIZh46bmjJRcMLg1KE00IA==,iv:51yE65xq95iCNBJuLBiJAz+Oj8n2gijDG/T7ublNGTs=,tag:le32yTRFKYVraBNxisWQrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjljbGIrNXlnb3AveHBk
            TmRWcHkrdVJ4NVRwZjF0VEowSWdnVWRwUFM4CjJuOVpjaHU1KzBKcWtWRzJaMlFa
            bTR3VGQ4d1NGQWJyaE13anZhMW8ydGsKLS0tIDlpcGRaeWFSYjRVMnBCTXNpTGhh
            Z2JoZzlQdVdPd2FOT2RvUmhnYUorZFUKZHk4mDdTdBosdWbP18uk4iCcTuyanynZ
            tsTjC6YkQ25z3rdoqBGMxsuIitNcNyBhczhid7tSltHiIk8B+yqpNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T02:49:13Z"
    mac: ENC[AES256_GCM,data:n+CIMJ60OzPbhQcQPjrqPy/KON+Teldkiq5NIuco5cTpwYV2rc5/SxaWbRlCFZcEYDPW+w7sC9ZuQhHBMk/OtecWUFZNdcoZFwzBgUfoIwhbAEuVEsdR238JQRwykpatgaeqvU4Vp2XGZiGLF8w5kl1H7xsSlxxR9ceh37QoYgI=,iv:g0JxLfHi92bxgaK9knB7/4GqEcxiPbOWgdr9q50bP/k=,tag:7h3Icih18upL+VSrXrmTHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
