apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:RPkhEcweRBD1ftQw64kF3frDfvoHv32v9Sq1ACJgBEEzpLuWTX3rzsYvw2NrFORAhSW2/AmiTL3NC9MI/lzHXMNmYy3U09jsGgedDGWkAw364B1077ytmt2wdZQL3w==,iv:ugPL/4s/ZrJwQ161usHGcYVqyqb/51M3xdQVhEDcYw8=,tag:wk7nj6D+gMnhY2UGQ1m8pQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:8sbVt3MPLLrBkYs=,iv:lqJnb0lsXO0geodUd4DhM3PbrPX4r+mRKDRD0TXFQuY=,tag:R4XwC08+IFCPT/abigtFwA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QOfV5KMWKpy599TGQs0p3xD6kYl2eg==,iv:fB8LJkNw8/pd19npGY77zFDEPGES0fgVlTBGxm+LWuU=,tag:7fERHjx8vgbq6biGQXksyA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:aNOw4d40ahIQ97TP4HX+R9/YfkZf7Etl2Jn7H8fqwkOME43D,iv:Zxfw5+uNsZKh+K9nndfhW7DwAS/QKIu8uVy5RrE+uFo=,tag:P8S74dLaYTrEmxXgz8RCYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdnZOMXByb014Y1NWYS9i
            UGVIQWlBRzdlQSs5SmdlVi9OeWVRQ3B4ZlVFCmhmbm9mVjIrdzRsMHhQMSsvL2g0
            dGdrcHNBQ2x3MG1GSEV3dHJLV2NBMzQKLS0tIExpcC9zL2UzdmlBYlhLaU4zMC8v
            dVFiOVZmRWIyTWVmRklzdmcySnVGZ1UKIL6E7xFgDRKfcV4kXWsVZ8alHlrT6hQs
            EcXhRhE6rqTHk54RGg6LIo+YED1JDESRCSejWDKDDFcSCzmanRNNzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T19:48:53Z"
    mac: ENC[AES256_GCM,data:lB6aTtgDltSLJjybVum98drAuGeAwzHstDzQvJ36cNfrvamFDI1djQYgLuqkf0nRQOpJ8MqWDEkpiU+LNBgYkSyAXH60jHlHNbfOINBTlyq1sZ93ejfS0IZjNplYUdneQr5R6RhtZPm7FI8gDKS0OG3ZMcrgsRKb6nqNQb477KY=,iv:UbOetGgISB02axsPkejxcjBIN5NOEIQgnFCE+PQcVmU=,tag:c10VQuFghtCrjwAxztuFaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
