# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.3
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.1

clusterName: &cluster home-kubernetes
endpoint: https://192.168.1.169:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"
additionalApiServerCertSans: &sans
  - "192.168.1.169"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans
cniConfig:
  name: none

nodes:
  - hostname: "bedroom1"
    ipAddress: "192.168.1.193"
    installDiskSelector:
      serial: "S6S1NS0TB05168W"
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - "192.168.1.193/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.1.1"
        vip:
          ip: "192.168.1.169"
  - hostname: "bedroom2"
    ipAddress: "192.168.1.194"
    installDiskSelector:
      serial: "AA2022092560004802"
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - "192.168.1.194/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.1.1"
        vip:
          ip: "192.168.1.169"
  - hostname: "bedroom3"
    ipAddress: "192.168.1.195"
    installDisk: "/dev/sdb"
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - "192.168.1.195/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.1.1"
  - hostname: "desk2.168.1.196"
    ipAddress: ""
    installDiskSelector:
      serial: "23384390BDDB"
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - "/24"
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.1.1"
        vip:
          ip: "192.168.1.169"

controlPlane:
  schematic:
    id: b531e671d84f29c9b4f79ecaabf0c9523aed503a8428f244d7262ba787e01ac3
    customization:
      systemExtensions:
  patches:
    # Configure containerd
    - &containerdPatch |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false

    # Disable search domain everywhere
    - &disableSearchDomainPatch |-
      machine:
        network:
          disableSearchDomain: true

    # Enable cluster discovery
    - &discoveryPatch |-
      cluster:
        discovery:
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: false

    # Configure kubelet
    - &kubeletPatch |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: true
          nodeIP:
            validSubnets:
              - "192.168.1.0/24"

    # Enable KubePrism
    - &kubePrismPatch |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # Force nameserver
    - &nameserverPatch |-
      machine:
        network:
          nameservers:
            - 1.1.1.1

    # Configure NTP
    - &ntpPatch |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com

    # Custom sysctl settings
    - &sysctlPatch |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: 65536
          fs.inotify.max_user_watches: 524288
          fs.inotify.max_user_instances: 8192

    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - "192.168.1.0/24"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:operator
            allowedKubernetesNamespaces:
              - system-upgrade

worker:
  schematic:
    id: b531e671d84f29c9b4f79ecaabf0c9523aed503a8428f244d7262ba787e01ac3
    customization:
      systemExtensions:
  patches:
    - *containerdPatch
    - *disableSearchDomainPatch
    - *discoveryPatch
    - *kubeletPatch
    - *kubePrismPatch
    - *nameserverPatch
    - *ntpPatch
    - *sysctlPatch
