apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:15qbf/6jdLBY8aA/JyCFQhZ5thl0j8rp8PbTSAFQXu0=,iv:zAPF4LbCoCHea40WJSeT1VL0q9C14DahkXksLv+nNGI=,tag:FWK2G75j4BUAVKIHvF231A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVklWdHVMU2xySUJHUVg2
            N1hhQUdrMU1HYmJvVnZXdlIyUGhiUVYxNDE4Ck94b0pwZGRNWTZBN3NxQXZkalZR
            THN5emtyckVjVHkyY0JxS3lhRy9TNnMKLS0tIHBHNElpQWNJenNMZ21VRkpsWEZK
            eldWckMwMk5yODI1M1lZRUZISHZXOFkKfbKiwq2KUXgDXyVk42d8/atd1eli5JoQ
            wybsFMo2qALXUpjaHa26pEIGOw03HdkSABfAm3rqTwGHDcR8cpFaOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T19:41:38Z"
    mac: ENC[AES256_GCM,data:wyIe4BlIgXp8w8GC6hGWXzavFJBUTNTEyuiaITq5NwE4NW5LA+Ctrw1v4s4zzeGn3IyOboOP2GJFwHUuZuc/N7aF/VcvqT8TJD5L+GMOl7fyw8Xf74pcWg+FS9HARSL969pAWKvN2LgvXO3U2gI14/+qWXerWyR7FPLaWV5fTzs=,iv:oWa36Q97cBSUd8t+bbMXApfMiKtp8mMqRH+Qn2kQZdg=,tag:aOkRIW9zBGVhoJTNmuHhvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
