apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3Cg5MqhGwZHy8DJLh8NJPPSe8+tqkuZ9VjyT8Ija9np1ggdXk3Mb7g==,iv:Gqa255svaGlS89r+P7mECNvZmJtrj1W4SNKSdkutHmg=,tag:RqCUpNXR0f1fC9PonXq9CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NkkxaXdueHdqQkRsdmRt
            SWdPSFYvUkdnTjJxOWNEVXhnZWNKRWRqVXo4CkVydUR1M2U3YzJZeFd6UDkwZ2RZ
            dm9TS1dqTVh5Ym1iYjV2Y3VRK0pCWWcKLS0tIDZUSlh5SFFBaVdlQTFoVGF4RFlT
            NFl5Q0pWSi9ma3JtMEJKQTh2enA2dDAK2rE1/amCmvMmFeGyoF9Eaf0kVpg7alXS
            jcYG1ssWSIoojdg7PrdezSeraqzOpRpgDLHIBHa6gNsvq0GeAK5aRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T03:21:32Z"
    mac: ENC[AES256_GCM,data:Ep3VQf97cbbvmTv3rDa6pOWt7POTgmk1wheBWLQpB+j+fT53X0fPmVKu/SFIsC7F6m5PsLCDz3+TS2tLcwrZ4t5CsouHA8/VHVcN9/c66YnXj5XnrQUA5T+iowBh44DLOxTr+aCLKqwBneR96lPejrqGa/q4MN++zfyvnbuQEGw=,iv:RxzEykw+ewG+gi2BzevBaZfJKSw36j6lBWYisea19xA=,tag:J+jMPpcRiqL9GfbDC22h0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
