apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:c7d1nhSevjlxLD8uJAKh++K6fktMNmghPHK9GOvFP4UXKP2+1Rvhkg==,iv:WRastQYqXQTSWFhJ79qKnhLvNnxLP4vYmiNf/vihilA=,tag:osRVhj+0kd0Nqo55dRECGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gmh6pkjz740tn9hh3xqnmtztkkau93ngrpgypdcqls0895e8y2qkgnmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVkxS2R6bnR2RTJiV2tB
            K0pmQ1FJUVdPbWRkaW5XN2pnMEVKZ3FXalIwCkRuZmxmUGh0VGtOZitHamNWSE1M
            TjRQNFdQMEtackpXQ2diSjRyZVIyNDQKLS0tIGVqOHUyei9yTGN1bU5jVGZoVUZ3
            OGl4SVpCWUkvTERwR3FGenpFMVlSdUkK5ZkUjT4FiRWloqSRiSbxWhs2A4kHTvs6
            TQnt70N/m/YEb9wSe3aTtMJ8yvB0bgVmcbpudiV6m7VdlQ2Zee7SuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T19:41:38Z"
    mac: ENC[AES256_GCM,data:zJLGv7rAjeusbCIPbndHYWIR+uIk/8E3cBfzKrUddkAiSaGF8b6kTMbAmqJXeG7Ta07HOoO6VzT+0uQYH8UpqSwQZNo9TQ6LDETHXl9MpdWJd+93eMJPMX7cTa8i8Zf5gT2OLySZvCm/Kp6tWvn9fBTgwAAJFrc9F9A3qXzyEGs=,iv:pqQ8tcx2x73dQM5bYMM5+1BJtI6h5MPTV03I4B2izb0=,tag:FRBp7FTzHduFL2QRev6HOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
